spring:
  mvc:
    servlet:
      path: /api
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/db-vehicle
    username: sa
    password:
    driverClassName: org.h2.Driver